const data = [
  {
    id: 1,
    sourceId: "SRC001",
    date: "2024-02-16",
    status: "Shipped",
    customer: "John Doe",
    email: "john@example.com",
    country: "USA",
    shipping: "$10",
    source: "Online",
    orderType: "Retail",
  },
  {
    id: 2,
    sourceId: "SRC002",
    date: "2024-02-17",
    status: "Pending",
    customer: "Jane Smith",
    email: "jane@example.com",
    country: "Canada",
    shipping: "$15",
    source: "In-store",
    orderType: "Wholesale",
  },
  {
    id: 3,
    sourceId: "SRC003",
    date: "2024-02-18",
    status: "Completed",
    customer: "Michael Johnson",
    email: "michael@example.com",
    country: "UK",
    shipping: "$20",
    source: "Online",
    orderType: "Retail",
  },
  {
    id: 4,
    sourceId: "SRC004",
    date: "2024-02-19",
    status: "Shipped",
    customer: "Emily Brown",
    email: "emily@example.com",
    country: "Australia",
    shipping: "$12",
    source: "In-store",
    orderType: "Retail",
  },
  {
    id: 5,
    sourceId: "SRC005",
    date: "2024-02-20",
    status: "Pending",
    customer: "David Wilson",
    email: "david@example.com",
    country: "Germany",
    shipping: "$18",
    source: "Online",
    orderType: "Wholesale",
  },
  {
    id: 6,
    sourceId: "SRC006",
    date: "2024-02-21",
    status: "Completed",
    customer: "Sarah Lee",
    email: "sarah@example.com",
    country: "France",
    shipping: "$22",
    source: "In-store",
    orderType: "Retail",
  },
  {
    id: 7,
    sourceId: "SRC007",
    date: "2024-02-22",
    status: "Shipped",
    customer: "Daniel Martinez",
    email: "daniel@example.com",
    country: "Spain",
    shipping: "$14",
    source: "Online",
    orderType: "Retail",
  },
  {
    id: 8,
    sourceId: "SRC008",
    date: "2024-02-23",
    status: "Pending",
    customer: "Olivia Garcia",
    email: "olivia@example.com",
    country: "Italy",
    shipping: "$16",
    source: "In-store",
    orderType: "Wholesale",
  },
  {
    id: 9,
    sourceId: "SRC009",
    date: "2024-02-24",
    status: "Completed",
    customer: "Ethan Anderson",
    email: "ethan@example.com",
    country: "Japan",
    shipping: "$25",
    source: "Online",
    orderType: "Retail",
  },
  {
    id: 10,
    sourceId: "SRC010",
    date: "2024-02-25",
    status: "Shipped",
    customer: "Ava Taylor",
    email: "ava@example.com",
    country: "Brazil",
    shipping: "$30",
    source: "In-store",
    orderType: "Retail",
  },
  {
    id: 11,
    sourceId: "SRC011",
    date: "2024-02-26",
    status: "Pending",
    customer: "Noah Hernandez",
    email: "noah@example.com",
    country: "Russia",
    shipping: "$35",
    source: "Online",
    orderType: "Wholesale",
  },
  {
    id: 12,
    sourceId: "SRC012",
    date: "2024-02-27",
    status: "Completed",
    customer: "Sophia Lopez",
    email: "sophia@example.com",
    country: "India",
    shipping: "$40",
    source: "In-store",
    orderType: "Retail",
  },
  {
    id: 13,
    sourceId: "SRC013",
    date: "2024-02-28",
    status: "Shipped",
    customer: "Logan Martinez",
    email: "logan@example.com",
    country: "China",
    shipping: "$45",
    source: "Online",
    orderType: "Retail",
  },
  {
    id: 14,
    sourceId: "SRC014",
    date: "2024-02-29",
    status: "Pending",
    customer: "Isabella Perez",
    email: "isabella@example.com",
    country: "South Africa",
    shipping: "$50",
    source: "In-store",
    orderType: "Wholesale",
  },
  {
    id: 15,
    sourceId: "SRC015",
    date: "2024-03-01",
    status: "Completed",
    customer: "Mia Carter",
    email: "mia@example.com",
    country: "South Korea",
    shipping: "$55",
    source: "Online",
    orderType: "Retail",
  },
  {
    id: 16,
    sourceId: "SRC016",
    date: "2024-03-02",
    status: "Shipped",
    customer: "James Adams",
    email: "james@example.com",
    country: "Mexico",
    shipping: "$60",
    source: "In-store",
    orderType: "Retail",
  },
  {
    id: 17,
    sourceId: "SRC017",
    date: "2024-03-03",
    status: "Pending",
    customer: "Charlotte Nelson",
    email: "charlotte@example.com",
    country: "Argentina",
    shipping: "$65",
    source: "Online",
    orderType: "Wholesale",
  },
  {
    id: 18,
    sourceId: "SRC018",
    date: "2024-03-04",
    status: "Completed",
    customer: "Elijah White",
    email: "elijah@example.com",
    country: "Chile",
    shipping: "$70",
    source: "In-store",
    orderType: "Retail",
  },
  {
    id: 19,
    sourceId: "SRC019",
    date: "2024-03-05",
    status: "Shipped",
    customer: "Amelia Scott",
    email: "amelia@example.com",
    country: "Peru",
    shipping: "$75",
    source: "Online",
    orderType: "Retail",
  },
  {
    id: 20,
    sourceId: "SRC020",
    date: "2024-03-06",
    status: "Pending",
    customer: "Benjamin Green",
    email: "benjamin@example.com",
    country: "Australia",
    shipping: "$80",
    source: "In-store",
    orderType: "Wholesale",
  },
];

export default data;
